from django.urls import path, include
from . import views

urlpatterns = [
    path('login', views.login),
    path('get_user_type', views.get_user_type),
    path('create', views.create),
    path('update_password', views.update_password),
    path('get_info', views.get_user_info),
    path('update_info', views.update_user_info),
    path('get_selection_res', views.get_selection_result),
    path('get_resume', views.get_resume),
    path('get_institute_info', views.get_institute_info),
    path('get_round_time', views.get_round_time),
    path('get_announcement', views.get_announcement),
    path('submit_announcement', views.submit_announcement),
    path('student/update_resume', views.update_resume),
    path('student/get_teachers', views.get_teachers),
    path('student/get_teachers_by_institute', views.get_teachers_by_institute),
    path('student/update_selection', views.update_selection),
    path('teacher/upload_resume', views.upload_resume),
    path('teacher/get_students', views.get_students),
    path('teacher/update_students', views.update_students_list),
    path('teacher/submit_selections', views.submit_selections),
    path('teacher/export', views.export_excel),
    path('admin/students', views.get_all_students),
    path('admin/teachers', views.get_all_teachers),
    path('admin/teachers_by_institute', views.get_all_teachers_by_institute),
    path('admin/get_round_selection', views.get_round_selection),
    path('admin/open_selection', views.open_selection),
    path('admin/get_no_action_teachers', views.get_no_action_teachers),
    path('admin/get_no_action_students', views.get_no_action_students),
    path('admin/automatically_assign_teacher', views.automatically_assign_teacher),
    path('admin/submit_distribution', views.submit_distribution),
    path('admin/get_teacher_confirm_res', views.get_teacher_confirm_res),
]
