# Generated by Django 2.2.10 on 2020-02-22 08:24

import backend.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=12, verbose_name='登录账号')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('grade', models.CharField(default='', max_length=50, verbose_name='管理年级')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=50, verbose_name='学生姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('Avatar', models.ImageField(upload_to=backend.models.get_path, verbose_name='学生头像')),
                ('grade', models.CharField(default='', max_length=4, verbose_name='年级')),
                ('college', models.CharField(default='', max_length=50, verbose_name='学院名称')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='专业名称')),
                ('class_name', models.CharField(default='', max_length=50, verbose_name='班级名称')),
                ('profile', models.TextField(default='', verbose_name='个人简介')),
                ('award', models.TextField(default='', verbose_name='获奖情况')),
                ('agree_distribution', models.BooleanField(default=False, verbose_name='接受分配')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='工号')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=50, verbose_name='教师姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('Avatar', models.ImageField(upload_to=backend.models.get_path, verbose_name='教师头像')),
                ('college', models.CharField(default='', max_length=50, verbose_name='学院名称')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='导师方向')),
                ('profile', models.TextField(default='', verbose_name='个人简介')),
                ('award', models.TextField(default='', verbose_name='获奖情况')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=True, verbose_name='是否为第一志愿导师')),
                ('pass_status', models.IntegerField(choices=[(0, '待通过'), (1, '通过'), (2, '未通过')], verbose_name='通过情况')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Student', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Teacher', verbose_name='导师')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='', max_length=4, verbose_name='年级')),
                ('content', models.TextField(verbose_name='公示内容')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始公示时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='公示结束时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Administrator', verbose_name='发布者')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='', max_length=4, verbose_name='年级')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始开放时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='公示开放时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Administrator', verbose_name='开放者')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('publicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Publicity', verbose_name='公示')),
            ],
        ),
    ]
