# Generated by Django 2.2.10 on 2020-02-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.CharField(default='', max_length=50, verbose_name='导师研究机构'),
        ),
    ]
