# Generated by Django 2.2.10 on 2020-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200227_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0, verbose_name='绩点'),
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.CharField(default='', max_length=50, verbose_name='绩点排名'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='pass_status',
            field=models.IntegerField(choices=[(0, '待通过'), (1, '通过'), (2, '未通过')], default=0, verbose_name='通过情况'),
        ),
    ]
