# Generated by Django 2.2.10 on 2020-03-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200303_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingtime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='openingtime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='openingtime',
            name='round',
            field=models.IntegerField(default=0, verbose_name='第几轮'),
        ),
        migrations.AddField(
            model_name='openingtime',
            name='s_end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='学生选择结束时间'),
        ),
        migrations.AddField(
            model_name='openingtime',
            name='s_start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='学生选择开始时间'),
        ),
        migrations.AddField(
            model_name='openingtime',
            name='t_end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='教师反选结束时间'),
        ),
        migrations.AddField(
            model_name='openingtime',
            name='t_start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='教师反选开始时间'),
        ),
        migrations.AddField(
            model_name='selection',
            name='round',
            field=models.IntegerField(default=0, verbose_name='第几轮结果'),
        ),
    ]
