# Generated by Django 2.2.10 on 2020-03-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200305_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=50, verbose_name='学院名称')),
                ('name', models.CharField(default='', max_length=50, verbose_name='导师研究机构')),
                ('introduction', models.TextField(verbose_name='简介')),
            ],
        ),
        migrations.AlterField(
            model_name='selection',
            name='pass_status',
            field=models.IntegerField(choices=[(0, '通过'), (1, '待通过'), (2, '未通过')], default=1, verbose_name='通过情况'),
        ),
    ]
