# Generated by Django 2.2.10 on 2020-03-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200307_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingtime',
            name='t_end_time',
        ),
        migrations.RemoveField(
            model_name='openingtime',
            name='t_start_time',
        ),
    ]
