# Generated by Django 2.2.10 on 2020-03-07 08:19
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200307_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicity',
            name='publicity_type',
            field=models.IntegerField(choices=[(0, '开放公告'), (1, '公示公告'), (2, '普通公告')], default=2, verbose_name='公示类别'),
        ),
        migrations.AddField(
            model_name='publicity',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name='开始时间'),
        ),
    ]
